spring:
  application:
    name: Simple App
  data:
    mongodb:
      uri: mongodb+srv://user_name:your_password@cluster0.wqgvb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: JournalDb
      auto-index-creation: true
server:
  port: 8081
  servlet:
    context-path: /journal


# Apart from application.properties and application.yaml files we can also assign the value using command line argument
# Example: com.your_repo_1.your_repo_2.your_repo_3.target> java -jar your_application_jar_name --properties server.port = 9093

# So, Precedence will be give to properties in following way-->
# 1. Command Line Argument
# 2. application.properties file
# 3. application.yaml file